CREATE TABLE Habitacion (
  habitacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_habitacion VARCHAR2(10),
  piso NUMBER,
  categoria VARCHAR2(20) CHECK (categoria IN ('turista','premium')),
  capacidad NUMBER,
  precio_diario NUMBER(10,2),
  estado VARCHAR2(20) DEFAULT 'disponible'
);

CREATE TABLE Usuario (
  usuario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100),
  apellido VARCHAR2(100),
  correo VARCHAR2(100) UNIQUE NOT NULL,
  telefono VARCHAR2(20),
  password_hash VARCHAR2(200) NOT NULL,
  rol VARCHAR2(20) CHECK (rol IN ('cliente','admin','empleado')),
  idioma_preferido VARCHAR2(10) DEFAULT 'ES'
);

CREATE TABLE Reserva (
  reserva_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id NUMBER NOT NULL,
  habitacion_id NUMBER NOT NULL,
  fecha_entrada DATE NOT NULL,
  fecha_salida DATE NOT NULL,
  cantidad_personas NUMBER,
  monto_total NUMBER(10,2),
  monto_anticipo NUMBER(10,2),
  estado VARCHAR2(20) DEFAULT 'pendiente',
  codigo_qr VARCHAR2(500),
  CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES Usuario(usuario_id),
  CONSTRAINT fk_habitacion FOREIGN KEY (habitacion_id) REFERENCES Habitacion(habitacion_id)
);

CREATE TABLE Pago (
  pago_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id NUMBER NOT NULL,
  monto NUMBER(10,2),
  fecha_pago DATE DEFAULT SYSDATE,
  metodo_pago VARCHAR2(50),
  estado_pago VARCHAR2(20) DEFAULT 'confirmado',
  CONSTRAINT fk_reserva FOREIGN KEY (reserva_id) REFERENCES Reserva(reserva_id)
);

CREATE TABLE FotoHabitacion (
  foto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  habitacion_id NUMBER NOT NULL,
  url_imagen VARCHAR2(300),
  CONSTRAINT fk_habitacion_foto FOREIGN KEY (habitacion_id) REFERENCES Habitacion(habitacion_id)
);
