-- ===========================
-- CREACIÓN DE TABLAS
-- ===========================

CREATE TABLE Usuario (
    usuario_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(50) NOT NULL,
    apellido        VARCHAR2(50) NOT NULL,
    correo          VARCHAR2(100) UNIQUE NOT NULL,
    telefono        VARCHAR2(20),
    password_hash   VARCHAR2(200) NOT NULL,
    rol             VARCHAR2(20) CHECK (rol IN ('Cliente', 'Administrador', 'Trabajador')),
    idioma_preferido VARCHAR2(20) CHECK (idioma_preferido IN ('Espanol', 'Ingles'))
);

CREATE TABLE Habitacion (
    habitacion_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero          NUMBER NOT NULL,
    categoria       VARCHAR2(20) CHECK (categoria IN ('Turista', 'Premium')),
    capacidad       NUMBER NOT NULL,
    precio_diario   NUMBER(10,2) NOT NULL,
    estado          VARCHAR2(20) CHECK (estado IN ('Disponible', 'Ocupada', 'Mantenimiento')),
    equipamiento    VARCHAR2(4000) 
);

CREATE TABLE FotoHabitacion (
    foto_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habitacion_id   NUMBER NOT NULL,
    url_imagen      VARCHAR2(500) NOT NULL,
    CONSTRAINT fk_foto_habitacion FOREIGN KEY (habitacion_id)
        REFERENCES Habitacion (habitacion_id)
);

CREATE TABLE Reserva (
    reserva_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      NUMBER NOT NULL,
    habitacion_id   NUMBER NOT NULL,
    fecha_entrada   DATE NOT NULL,
    fecha_salida    DATE NOT NULL,
    cantidad_personas NUMBER NOT NULL,
    monto_total     NUMBER(10,2) NOT NULL,
    pago_reserva    NUMBER(10,2) NOT NULL,
    estado          VARCHAR2(20) CHECK (estado IN ('Pendiente', 'Confirmada', 'Cancelada')),
    codigo_qr       VARCHAR2(200),
    CONSTRAINT fk_reserva_usuario FOREIGN KEY (usuario_id)
        REFERENCES Usuario (usuario_id),
    CONSTRAINT fk_reserva_habitacion FOREIGN KEY (habitacion_id)
        REFERENCES Habitacion (habitacion_id)
);

CREATE TABLE Pago (
    pago_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id      NUMBER NOT NULL,
    monto           NUMBER(10,2) NOT NULL,
    fecha_pago      DATE NOT NULL,
    metodo_pago VARCHAR2(50) CHECK (metodo_pago IN ('Tarjeta', 'Transferencia', 'Efectivo', 'PayPal')),
    CONSTRAINT fk_pago_reserva FOREIGN KEY (reserva_id)
        REFERENCES Reserva (reserva_id)
);

CREATE TABLE Reporte (
    reporte_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      NUMBER NOT NULL,
    tipo            VARCHAR2(50),
    fecha_generacion DATE DEFAULT SYSDATE,
    CONSTRAINT fk_reporte_usuario FOREIGN KEY (usuario_id)
        REFERENCES Usuario (usuario_id)
);
